runtime: python39

env_variables:
  ENVIRONMENT: production
  DEBUG: False

handlers:
  # Serve static files
  - url: /static
    static_dir: staticfiles/
    secure: always

  # Serve media files
  - url: /media
    static_dir: media/
    secure: always

  # Main application
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: 10s

resources:
  cpu: 4.0
  memory_gb: 16
  disk_size_gb: 20

entrypoint: gunicorn -b :$PORT cloud_detection_portal.wsgi:application --timeout 900 --workers 3 --threads 4 --worker-class sync 