# Generated by Django 4.2.7 on 2025-07-04 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='satellite_data/')),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('processing_start_time', models.DateTimeField(blank=True, null=True)),
                ('processing_end_time', models.DateTimeField(blank=True, null=True)),
                ('satellite_name', models.CharField(default='INSAT', max_length=100)),
                ('data_type', models.CharField(default='HDF5', max_length=50)),
                ('observation_time', models.DateTimeField(blank=True, null=True)),
                ('brightness_temperature_plot', models.FileField(blank=True, null=True, upload_to='results/brightness_temp/')),
                ('cloud_mask_plot', models.FileField(blank=True, null=True, upload_to='results/cloud_mask/')),
                ('processed_data_file', models.FileField(blank=True, null=True, upload_to='results/processed_data/')),
                ('total_pixels', models.IntegerField(blank=True, null=True)),
                ('cloud_pixels', models.IntegerField(blank=True, null=True)),
                ('cloud_coverage_percentage', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Satellite Data',
                'verbose_name_plural': 'Satellite Data',
                'ordering': ['-upload_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=20)),
                ('message', models.TextField()),
                ('satellite_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cloud_detection.satellitedata')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
