# Generated by Django 4.2.7 on 2025-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitedata',
            name='avg_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='cloud_cluster_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='max_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='max_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='max_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='min_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='min_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='min_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='weather_conditions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
