# Generated by Django 4.2.7 on 2025-07-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_detection', '0004_remove_satellitedata_gcs_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitedata',
            name='gcs_bucket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='gcs_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='upload_source',
            field=models.CharField(choices=[('direct', 'Direct Upload'), ('gcs', 'Google Cloud Storage')], default='direct', max_length=20),
        ),
    ]
